version: '2.2'
services:

  workshop-management-system-jama:
    image: workshop-management-system-jama
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: workshop-management-system-jama
    ports:
     - "8008:80"
    restart: "always"
    networks:
      - nginx-network

networks:
  nginx-network:
    external:
      name: nginx-network
